version: '3.4'

networks:
    backend:
    frontend:

services:
  apigateway:
    container_name: api-gateway
    image: ${DOCKER_REGISTRY-}api-gateway
    build:
      context: .
      dockerfile: APIGateway/Dockerfile
    ports:
        - 45001:80
    networks:
        - backend

  cataloguewebapi:
    container_name: catalogue-api
    image: ${DOCKER_REGISTRY-}catalogue-api
    ports:
        - 45002:443  
        - 65447:80  
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    networks:
        - backend


